language: go

go:
    - master

env:
    global:
        - SSH_KEY="travis_key"
        - GIT_NAME="Isulew Li"
        - GIT_EMAIL="netcookies@gmail.com"
        - SOURCE_DIR="public"
        - DEPLOY_BRANCH="source"

before_install:
    - openssl aes-256-cbc -K $encrypted_1d72df0a25ac_key -iv $encrypted_1d72df0a25ac_iv -in travis_key.enc -out travis_key -d

before_script:
    - git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
    - go get -u -v github.com/spf13/hugo

script:
    - git clone https://github.com/netcookies/cocoa-hugo-theme ./themes/cocoa
    - hugo -t cocoa

after_success:
    - echo "nznd.org" > ./public/CNAME
    - ./scripts/deploy.sh
